In [26]:
import numpy as np

In [2]:
a=np.array([[1,2,3],
              [4,5,6]])

<IPython.core.display.Javascript object>

In [3]:
# Two axis files are there in numpy
# 1.Column wise 2. row wise 
a.sum(axis=1) # row wise sum  or x axis

array([ 6, 15])

In [4]:
a.sum(axis=0) # column wise or y axis

array([5, 7, 9])

In [6]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b=np.array([[7,8,9],
              [2,8,0]])

<IPython.core.display.Javascript object>

In [8]:
a.dot(b) # error bcz dot product same dimension ka nhi niklta
# Here 3*1 and 3 *1 is there we know matrix multiplication rule

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [9]:
# Dot
a.dot(b.transpose())

array([[ 50,  18],
       [122,  48]])

In [11]:
# to know functions of numpy you can use:
dir(np)

SyntaxError: incomplete input (1496971102.py, line 2)

In [13]:
# Dont learn numpy functions
len(dir(np))

<IPython.core.display.Javascript object>

599

In [16]:
a.cross(b)# cross function is not define on np array

AttributeError: 'numpy.ndarray' object has no attribute 'cross'

In [17]:
np.cross(a,b) #so for good practice use np.dot(a,b,transpose()) 

<IPython.core.display.Javascript object>

array([[ -6,  12,  -6],
       [-48,  12,  22]])

In [19]:
# Sorting
c=np.array([[5,2,11],
              [4,15,6]])

<IPython.core.display.Javascript object>

In [21]:
np.sort(c) # sort in axis 1 row wise

<IPython.core.display.Javascript object>

array([[ 2,  5, 11],
       [ 4,  6, 15]])

In [25]:
# For axis = 0
# Numpy array size changing is a expensive operator as its written in C
# dont make array compact and expand
np.sort(c,axis=0,kind="mergesort") # you can give kind of sort you want to apply.

<IPython.core.display.Javascript object>

array([[ 4,  2,  6],
       [ 5, 15, 11]])